### ISSUE TITLE
Restore forwarding may be problematic

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1088]
There are reports that restoring via a follower is not working correctly. I can't reproduce any issues.

**Test case 1: spin up a 2-node cluster by hand and restore through the follower.**

Start node 1:
```bash
rqlited -node-id 1 data.1
```
Start node 2 and join it to node 1:
```bash
rqlited -http-addr localhost:4003 -raft-addr localhost:4004 -join http://localhost:4001 -node-id 2 data.2
```

Restore a SQLite file into the cluster via the follower:
```bash
curl -v -XPOST localhost:4003/db/load -H "Content-type: application/octet-stream" --data-binary @restore.sqlite
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:4003...
* TCP_NODELAY set
* connect to ::1 port 4003 failed: Connection refused
*   Trying 127.0.0.1:4003...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4003 (#0)
> POST /db/load HTTP/1.1
> Host: localhost:4003
> User-Agent: curl/7.68.0
> Accept: */*
> Content-type: application/octet-stream
> Content-Length: 8192
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Rqlite-Served-By: localhost:4002
< X-Rqlite-Version: 7
< Date: Mon, 24 Oct 2022 13:30:57 GMT
< Content-Length: 14
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"results":[]}
```
Query the leader:
```bash
url -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "columns": [
                "id",
                "name"
            ],
            "types": [
                "integer",
                "text"
            ],
            "values": [
                [
                    1,
                    "fiona"
                ]
            ],
            "time": 0.000144014
        }
    ],
    "time": 0.000647214
}
```
Query the follower, using `none` consistency (so the local SQLite database is queried:
```bash
curl -G 'localhost:4003/db/query?pretty&timings?level=None' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "columns": [
                "id",
                "name"
            ],
            "types": [
                "integer",
                "text"
            ],
            "values": [
                [
                    1,
                    "fiona"
                ]
            ]
        }
    ]
}
```

**Test case 2: I did something very similar on Minikube, using the following configs, and restored fine through a follower** (the Load Balancer routed me to a follower).
Services:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: rqlite-svc-internal
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: rqlite-svc
spec:
  type: LoadBalancer
  selector:
    app: rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
```
Stateful set:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rqlite
spec:
  selector:
    matchLabels:
      app: rqlite # has to match .spec.template.metadata.labels
  serviceName: rqlite-svc-internal
  replicas: 3 # by default is 1
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: rqlite # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rqlite
        image: rqlite/rqlite:local2
        args: ["-disco-mode=dns","-disco-config={\"name\":\"rqlite-svc-internal\"}","-bootstrap-expect","3", "-join-interval=1s", "-join-attempts=120"]
        ports:
        - containerPort: 4001
          name: rqlite
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: rqlite-file
          mountPath: /rqlite/file
  volumeClaimTemplates:
  - metadata:
      name: rqlite-file
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
```
