### ISSUE TITLE
docker-compose started instance heartbeat timeout

### ISSUE THREAD

**Issue by nickarls** [rqlite/rqlite#1289]
if I start a single-node instance with docker run, it works fine.
If I start it through docker-compose, the heartbeat times out and the node is not elected leader, resulting in a 503 for queries

```
2023-06-01T10:33:46.598Z [INFO]  raft: entering follower state: follower="Node at 9a7f5b17f46b:4002 [Follower]" leader-address= leader-id=
2023-06-01T10:33:47.963Z [WARN]  raft: heartbeat timeout reached, not part of a stable configuration or a non-voter, not triggering a leader election
```

The stack is pretty much
```
  rqlite:
    container_name: rqlite
    image: rqlite/rqlite
    ports:
      - 4001:4001
    restart: always
    volumes:
      - rqlite-data:/rqlite/file/data
```
