### ISSUE TITLE
"fatal: arguments after data directory are not accepted" isn't helpful

### ISSUE THREAD

**Issue by bluepuma77** [rqlite/rqlite#1398]
**Is your feature request related to a problem? Please describe.**
I am trying to run rqlite with auto-clustering in Docker Swarm. I am using a `docker-compose.yml` file and receive "fatal: arguments after data directory are not accepted", which isn't really helpful, as I don't understand what rqlite is receiving.

**Describe the solution you'd like**
I would like rqlite to show the parameters it received, so I can understand better what is happening.

**Describe alternatives you've considered**
n/a

**Additional context**
Use `docker stack deploy -c docker-compose.yml rqlite && docker service logs -f --since 1s rqlite_rqlite`

```
version: '3'

networks:
  rqlite:
    name: rqlite
    driver: overlay
    attachable: true

services:
  rqlite:
    command:
      - -node-id={{.Task.Slot}}
      - -http-addr={{.Task.Name}}:4001
      - -raft-addr={{.Task.Name}}:4002
      - -disco-mode=dns
      - -disco-config='{"name":"rqlite"}'
      - -bootstrap-expect=3
      - data
    deploy:
       mode: replicated
       replicas: 3
       endpoint_mode: dnsrr      
    image: rqlite/rqlite
    networks:
      - rqlite
```

**Comment by otoolep** [comment]
I'm assuming you're running the latest Docker image: https://github.com/rqlite/rqlite-docker/blob/master/7.21.4/docker-entrypoint.sh

Agreed, that log message could be more helpful. But I think I know what might be happening -- don't pass `data` as one of the commands. The Docker image always uses `/rqlite/file/data` unless it is overridden by the environment variable, `DATA_DIR`. If the default path ( `/rqlite/file/data`) is not acceptable to you, then set `DATA_DIR` to whatever you want it to be. I presume Docker Swarm will allow you to set the environment which is passed to the launch process.

So change your Docker compose file to the following:
```yaml
version: '3'

networks:
  rqlite:
    name: rqlite
    driver: overlay
    attachable: true

services:
  rqlite:
    command:
      - -node-id={{.Task.Slot}}
      - -http-addr={{.Task.Name}}:4001
      - -raft-addr={{.Task.Name}}:4002
      - -disco-mode=dns
      - -disco-config='{"name":"rqlite"}'
      - -bootstrap-expect=3
    deploy:
       mode: replicated
       replicas: 3
       endpoint_mode: dnsrr      
    image: rqlite/rqlite
    networks:
      - rqlite
```
