### ISSUE TITLE
"clustering failure: error reading DNS configuration: invalid character '\'' looking for beginning of value" isn't helpful [Docker Swarm]

### ISSUE THREAD

**Issue by bluepuma77** [rqlite/rqlite#1401]
**Is your feature request related to a problem? Please describe.**
I am trying to get rqlite up and running in Docker Swarm. The automatic clustering is not working, I don't know why. 

I enabled `endpoint_mode: dnsrr`, which I would expect to be compatible with [rqlite DNS for Bootstrapping](https://rqlite.io/docs/clustering/automatic-clustering/#using-dns-for-bootstrapping).

> Docker sets up DNS entries for the service such that a DNS query for the service name returns a list of IP addresses, and the client connects directly to one of these.

**Describe the solution you'd like**
Enable more debug output on this error, so it's easier to understand what is returned by the query. 

In general I would love a `-debug` flag to get some more infos during the startup process.
 
**Describe alternatives you've considered**
To check, I ran a Debian container on the same Docker network and used `dig rqlite A +short`, which shows up to 3 IPs, depending on the state of the continuously restarting containers.

**Additional context**
Use `docker stack deploy -c docker-compose.yml rqlite && docker service logs -f --since 1s rqlite_rqlite`
```
version: '3'

networks:
  rqlite:
    name: rqlite
    driver: overlay
    attachable: true

services:
  rqlite:
    command:
      - -disco-mode=dns
      - -disco-config='{"name":"rqlite"}'
      - -bootstrap-expect=3
    deploy:
       #mode: global
       mode: replicated
       replicas: 3
       endpoint_mode: dnsrr
    environment:
      - START_DELAY=5
      - NODE_ID={{.Task.ID}}
      - DATA_DIR=/rqlite/file/data
      - HTTP_ADV_ADDR={{.Task.Name}}:4001
      - RAFT_ADV_ADDR={{.Task.Name}}:4002
    image: rqlite/rqlite
    networks:
      - rqlite
    #volumes:
    #  - rqlite-volume:/data

#volumes:
#  rqlite-volume:      
```

Here is the log output:
```
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |             _ _ _
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |            | (_) |
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |   _ __ __ _| |_| |_ ___
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |  | '__/ _  | | | __/ _ \   The lightweight, distributed
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |  | | | (_| | | | ||  __/   relational database.
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |  |_|  \__, |_|_|\__\___|
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |          | |               www.rqlite.io
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |          |_|
rqlite_rqlite.3.p8ghpw4jmzx0@c2    |
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 rqlited starting, version v7.21.4, SQLite 3.42.0, commit 971921f1352bdc73e4e66a1ec43be8c1028ff18b, branch master, compiler gc
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 go1.20, target architecture is amd64, operating system target is linux
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 launch command: /bin/rqlited -node-id p8ghpw4jmzx03mug6hdiikd1t -http-addr 0.0.0.0:4001 -http-adv-addr rqlite_rqlite.3.p8ghpw4jmzx03mug6hdiikd1t:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr rqlite_rqlite.3.p8ghpw4jmzx03mug6hdiikd1t:4002 -disco-mode=dns -disco-config='{"name":"rqlite"}' -bootstrap-expect=3 /rqlite/file/data
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 Raft TCP mux Listener registered with byte header 1
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 no preexisting node state detected in /rqlite/file/data, node may be bootstrapping
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [cluster] 2023/09/14 14:10:48 service listening on rqlite_rqlite.3.p8ghpw4jmzx03mug6hdiikd1t:4002
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 cluster TCP mux Listener registered with byte header 2
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [http] 2023/09/14 14:10:48 execute queue processing started with capacity 1024, batch size 128, timeout 50ms
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [http] 2023/09/14 14:10:48 service listening on [::]:4001
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 HTTP server started
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 opening store with node ID p8ghpw4jmzx03mug6hdiikd1t
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 configured for an in-memory database
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 ensuring directory for Raft exists at /rqlite/file/data
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 0 preexisting snapshots present
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [mux] 2023/09/14 14:10:48 mux serving on [::]:4002, advertising rqlite_rqlite.3.p8ghpw4jmzx03mug6hdiikd1t:4002
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 first log index: 0, last log index: 0, last applied index: 0, last command log index: 0:
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [store] 2023/09/14 14:10:48 created in-memory database at open
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | 2023-09-14T14:10:48.155Z [INFO]  raft: initial configuration: index=0 servers=[]
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | 2023-09-14T14:10:48.155Z [INFO]  raft: entering follower state: follower="Node at rqlite_rqlite.3.p8ghpw4jmzx03mug6hdiikd1t:4002 [Follower]" leader-address= leader-id=
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 discovery mode: dns
rqlite_rqlite.3.p8ghpw4jmzx0@c2    | [rqlited] 2023/09/14 14:10:48 clustering failure: error reading DNS configuration: invalid character '\'' looking for beginning of value
```

PS: Sorry to bother so much

**Comment by bluepuma77** [comment]
Maybe it's a deadly cycle. All 3 `rqlite` containers come up at the same time, don't get any IP from discovery immediately, then exit. Then all get restarted at the same time. Maybe it needs an internal START_DELAY or a loop to try several times. 

Currently they seem to exit immediately after the error, without any notice of shutdown.
```
rqlite_rqlite.2.p1zh1wrxd9bo@c2    | [rqlited] 2023/09/14 14:23:31 discovery mode: dns
rqlite_rqlite.2.p1zh1wrxd9bo@c2    | [rqlited] 2023/09/14 14:23:31 clustering failure: error reading DNS configuration: invalid character '\'' looking for beginning of value
```

**Comment by otoolep** [comment]
You probably need to escape the disco-config settings, see https://github.com/rqlite/kubernetes-configuration/blob/master/statefulset-1-node.yaml

**Comment by bluepuma77** [comment]
Awesome, that was it! This works:
```
version: '3'

networks:
  rqlite:
    name: rqlite
    driver: overlay
    attachable: true

services:
  rqlite:
    command:
      - -disco-mode=dns
      - -disco-config={"name":"rqlite"}
      - -bootstrap-expect=3
    deploy:
       #mode: global
       mode: replicated
       replicas: 3
       endpoint_mode: dnsrr
    environment:
      #- START_DELAY=5
      - NODE_ID={{.Task.ID}}
      - DATA_DIR=/rqlite/file/data
      - HTTP_ADV_ADDR={{.Task.Name}}:4001
      - RAFT_ADV_ADDR={{.Task.Name}}:4002
    image: rqlite/rqlite
    networks:
      - rqlite
    #volumes:
    #  - rqlite-volume:/data

#volumes:
#  rqlite-volume:
```

@otoolep You want to add a Docker Swarm section to your [Automatic clustering](https://rqlite.io/docs/clustering/automatic-clustering/) page? That would be really cool!
