### ISSUE TITLE
How does -join-as work when auth file uses bcrypt-hashed passwords?

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1488]
Given this auth file:

```json
    [
      {
        "username": "rqlite",
        "password": "$2y$10$iU5Bxd9JTJHBlLnBrPAXa.pnCVCeCiNUUkrePSMZak7jkwbmnoO",
        "perms": ["all"]
      },
      {
        "username": "myapp",
        "password": "$2y$10$924DZWAmYSjxPR8H12.jvurK7lrZfKESSoogIb1fKJrvhLQ9PNcWa",
        "perms": ["all"]
      },
      {
        "username": "*",
        "perms": ["status", "ready"]
      }
    ]
```

Originally the cluster failed to assemble due to unauthorized calls.  So I tried passing `-join-as=rqlite` to rqlited and it's coming up.

The thing is, I didn't expect it to: the `rqlite` user's password is hashed, and the cleartext version doesn't exist anywhere for rqlited to read.

How is the inter-node auth working here?

**Comment by otoolep** [comment]
Thanks @jtackaberry -- you are right, this is broken (and has been for a long time unfortunately). The bcrypt form is not adding any value, and the system is doing a standard string compare.

From looking at the code, the best way to address this issue is update the docs. Password security *is* effective, in the sense once this file is present a given user must supply the right string, but obscuring it via hashing is pointless. And it could have been giving folks a false sense of security.

**Comment by otoolep** [comment]
I just updated the [Security page](https://rqlite.io/docs/guides/security/) to remove all references to bcrypt support. Definitely a bad issue in the code, thanks for flagging.

The root issue was due to some caching that was added a long time ago, to speed up authentication. It was then this issue was added.

**Comment by jtackaberry** [comment]
> The root issue was due to some caching that was added a long time ago, to speed up authentication

Ironically that feature was requested by me. :)

 So basically the hashed value was serving as a plaintext equivalent.  Thanks for the clarification @otoolep.  I'll revert to cleartext credentials and move the file from a K8s ConfigMap to a proper Secret.

**Comment by otoolep** [comment]
@jtackaberry -- could you tell me more about how you do this? What kind of config does one set up? I wouldn't mind adding the details to the rqlite.io docs.

**Comment by otoolep** [comment]
I don't need all the details, even general pointers and suggestions about how to securely store the file in practise.

**Comment by jtackaberry** [comment]
>could you tell me more about how you do this? What kind of config does one set up?

@otoolep it's just a matter of placing the user JSON in a K8s Secret and mounting it in the pod.  For example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rqlite
stringData:
  users.json: |-
    [
      {
        "username": "rqlite",
        "password": "ac6eRjAaMV6qWmyZt74Z5rTkje",
        "perms": ["all"]
      },
      {
        "username": "myapp",
        "password": "SaKm2gmCVfFA4vuw7u3horR9Ux",
        "perms": ["all"]
      },
      {
        "username": "*",
        "perms": ["status", "ready"]
      }
    ]
```

Then in the StatefulSet, you source the Secret as a volume in the pod template (`.spec.template.spec.volumes`):

```yaml
      volumes:
        - name: secrets
          secret:
            secretName: rqlite
```

Then in the container definition, you specify a mount point (`.spec.template.spec.containers[0].volumeMounts`):

```yaml
          volumeMounts:
            # Existing mount point for PV
            - name: storage
              mountPath: /rqlite
            # New mount point for Secrets
            - name: secrets
              mountPath: /secrets
              readOnly: true
```

Now the user file will be located at `/secrets/users.json`.  Then it's just a matter of passing `-auth=/secrets/users.json` to rqlited's command line arguments in the pod args.  Updates to the K8s Secret will automatically cause the mounted file to be updated as well (although I'm not sure if rqlite supports dynamic reloading if this file changes?). 

Kubernetes itself isn't prescriptive about how one secures the Secret manifest, but one common approach is to use Mozilla Sops to encrypt the manifest file in Git.  This also works very nicely for Helm charts using the popular [Helm secrets plugin](https://github.com/jkroepke/helm-secrets), where you can keep sensitive chart values in a Sops-encrypted file and it gets merged in with standard unencrypted values files when the chart is deployed.

Speaking of Helm, would you be interested in a Helm chart contribution?  I've built a chart for rqlite for my own use, and it really wouldn't take too much extra effort to clean it up properly and add a few missing features (notably support for TLS and read-only replicas), to make it suitable for more general use.
