### ISSUE TITLE
Helm chart for rqlite

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1495]
From #1488:

> What is a good way to share it with the community? A distinct repo in the rqlite org? You could have commit rights if you wish, if we create a brand new repo. Or do you want to make a pull request against https://github.com/rqlite/kubernetes-configuration? A distinct directory containing the suggestion configuration for Helm?

There seems to be an emerging de facto consensus for projects with dedicated GitHub orgs to have a `helm-charts` repo, with a structure `/charts/<name>`, and then using GitHub Actions to build and publish the chart at some website (commonly GH Pages) for deployments to use.  (Examples: [1](https://github.com/prometheus-community/helm-charts/
) [2](https://github.com/grafana/helm-charts
) [3](https://github.com/opensearch-project/helm-charts
) [4](https://github.com/fluent/helm-charts
).)  I'm inclined to do as the Romans do in this case. 

So a `rqlite/helm-charts` would be the most idiomatic.  rqlite's chart repo, if using GH Pages, would then be added by users like so:

```
helm repo add rqlite https://rqlite.github.io/helm-charts
```
In rqlite's case there would just be a single chart (`/charts/rqlite`) but who knows what the future has in store.  For example, stateful applications running in Kubernetes often have Kubernetes Operators to orchestrate app-specific behaviors, which could involve another chart.

I would be happy to act as maintainer for the chart.  If you wanted to create the repo and grant me a suitable level of access, I can get the ball rolling in a develop branch where we can go through an initial review process before it's merged to master.   As you might imagine, Helm charts are a delicate (often wrong) balance between having sufficient hooks/abstractions to support all kinds of reasonable deployments and the inevitable complexity that comes with it.  You'll have a much better idea of what a "reasonable deployment" is than me, so I'm very much interested in your review first.

My goals for the chart are:
  * Deploy a working single node and multi-node cluster out-of-the-box (modulo the replica count)
  * Handle the vast majority of rqlite deployment configurations through Helm chart values
  * Support the typical customizations offered by charts (extra pod labels and annotations, node selectors, affinity rules, pod topology spread constraints, etc.)
  * Support user (auth) definitions as YAML-based chart values (convenience, e.g. to permit commenting)
  * Support TLS for both client connections and inter-node communication (by means of allowing the required config for certs, etc.)
  * Allow for readonly replicas, independently scaled from the ... what *do* we call these?  masters?  voters?  writers?
  * Define a network policy that blocks access to the raft port except by other nodes in the rqlite cluster
  * Test on multiple K8s environments (probably EKS (AWS), LKE (Linode), and Microk8s (self-hosted) just based on what I use day to day)
  * Publish via GitHub actions

Thoughts?

**Comment by otoolep** [comment]
This all sounds great -- would be a substantial contribution to the rqlite community.  I've created the repo and granted you the "Maintainer" role, which gives you full commit rights and allows you to set up GitHub publishing actions for that repo. 

https://github.com/rqlite/helm-charts

>Allow for readonly replicas, independently scaled from the ... what do we call these? masters? voters? writers?

Voting nodes is the most-accurate term for nodes that are not read-only nodes (which are sometimes call non-voters).

**Comment by jtackaberry** [comment]
>  I've created the repo and granted you the "Maintainer" role, which gives you full commit rights and allows you to set up GitHub publishing actions for that repo.

Excellent.  I'll get cracking on it then and will have something committed in a dev branch within a couple days.

> Voting nodes is the most-accurate term for nodes that are not read-only nodes (which are sometimes call non-voters).

Part of the reason I asked about the terminology is I was thinking about how to structure the chart values for a separate pool of read-only nodes.  This would be a separate StatefulSet and Service, and it probably makes sense to allow independent configuration of each deployment, but also to be able to define common settings for both in the interest of DRY.

That being the case, the chart values would have a structure along the lines of:

```yaml

# Applies to both voter and readonly pools
common:
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  # ...

# Can override anything from common and only applies to the voter pool
voter:
  replicaCount: 3
  podLabels: {}
  podAnnotations: {}
  # ...

# Can override anything from common and only applies to the readonly pool
readonly:
  replicaCount: 4
  podLabels: {}
  podAnnotations: {}
  # ...
```

While I suppose "readonly pool" is idiomatic enough, "voter pool" sounds a bit alien.  But maybe that's perfectly cromulent in context.  I want to use the proper terminology in the chart.  Do you have any suggestions?

**Comment by jtackaberry** [comment]
Another option is to just accept that most deployments won't have read-only nodes (at least I assume this is uncommon), and tailor the chart's ergonomics to this more common use case by moving the leader configuration to the top level and relegating readonly overrides to a map:

```yaml
# Applies to all nodes by default
replicaCount: 3
podLabels: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
# ...

# Can override anything above but only applies to readonly nodes
readonly:
  replicaCount: 5
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  # ...
```
The asymmetry tweaks the OCD in me, but I think it makes it more straightforward to use for most deployments (which won't have readonly nodes).
