### ISSUE TITLE
Backup on medium size db via CLI crashes / excessively slow backups

### ISSUE THREAD

**Issue by Tjstretchalot** [rqlite/rqlite#1551]
**What version are you running?**
issue confirmed on v8.12.3 and v8.14.3

**Are you using Docker or Kubernetes to run your system?**
no

**Are you running a single node or a cluster?**
3 node cluster

**What did you do?**
`.backup dbbak.sqlite3` in CLI

**What did you expect to happen?**
Make a sqlite backup file at dbbak.sqlite3

**What happened instead?**
Either it times out the entire instance (I'm guessing OOM) until eventually a ^C goes through, or ends abruptly with
```
ERR! unexpected EOF
```

**My Analysis**
Happy new year!

A ~300MB database size with ~1GB free memory and ~1.6GB available memory w/o swap. Instance is behaving like it's consuming nearly all the memory, though its hard to confirm since SSH freezes while the backup is running

Note that a backup can proceed if done via curl in about 15 seconds, but notably it idles for 7 seconds and then downloads in 7 seconds, suggesting that the issue is that both the server and the client in rqlite are not streaming the backup, leading to a crazy multiple of the db size required as free memory when backing up from the local machine.

However, after further investigation, it appears that only the client is definitely doubling the memory usage, and the pause on the server response is not due to simply memory buffering (it copies to file)

However, looking at how the hot backup is created, I'm quite positive an alternative backup method would be _much_ faster for my use-case, assuming I'm not misunderstanding something and this is possible: reject unless not leader, reject all new incoming connections with 503, finish processing all running commands, pause Raft, copy sqlite3 file directly to writer, resume raft, resume incoming connections. The reason I believe this is faster is this is essentially what's currently happening anyway; the only difference is instead of 503's it just times out, and instead of the other nodes knowing the node is down, it doesn't happen for a second or two until the timeout is reached

what I looked at:

client does not stream the backup to the file, since it uses the standard sendRequest method: https://github.com/rqlite/rqlite/blob/9c9e911caa0583b070e78aaa8853e793d817bbc8/cmd/rqlite/backup.go#L48 https://github.com/rqlite/rqlite/blob/9c9e911caa0583b070e78aaa8853e793d817bbc8/cmd/rqlite/main.go#L496C25-L496C25

server does appear to stream the backup to some intermittent file ("main"?) https://github.com/rqlite/rqlite/blob/master/db/db.go#L1365 https://github.com/mattn/go-sqlite3/blob/master/backup.go#L28

the service does appear to be passing a writer to backup, which is a good sign it's streaming: https://github.com/rqlite/rqlite/blob/9c9e911caa0583b070e78aaa8853e793d817bbc8/http/service.go#L608C17-L608C23

for binary files it looks like rather than writing the result directly to the stream it instead writes it to a temporary file first, I'm guessing to set some pragmas? -> https://github.com/rqlite/rqlite/blob/9c9e911caa0583b070e78aaa8853e793d817bbc8/store/store.go#L1198 This would explain the long delay in the start without using excessive memory. It then io.Copy's, which should stream

---

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

leader:
```
[ec2-user@ip-10-0-4-241 ~]$ rqlite -H 10.0.6.13
Welcome to the rqlite CLI.
Enter ".help" for usage hints.
Connected to http://10.0.6.13:4001 running version v8.14.1
10.0.6.13:4001> .status
network:
  interfaces:
    ens5:
      flags: up|broadcast|multicast|running
      hardware_address: 0e:43:d0:4e:a0:7d
      addresses: [map[address:10.0.6.13/24] map[address:fe80::c43:d0ff:fe4e:a07d/64]]
    lo:
      flags: up|loopback|running
      hardware_address:
      addresses: [map[address:127.0.0.1/8] map[address:::1/128]]
node:
  uptime: 3m40.483247755s
  current_time: 2024-01-02T13:58:11.074704203Z
  start_time: 2024-01-02T13:54:30.591456931Z
os:
  page_size: 4096
  pid: 477562
  ppid: 477558
  executable: /usr/local/src/rqlite-v8.14.1-linux-arm64/rqlited
  hostname: ip-10-0-6-13.us-west-2.compute.internal
runtime:
  num_cpu: 2
  num_goroutine: 44
  version: go1.21.5
  GOARCH: arm64
  GOMAXPROCS: 2
  GOOS: linux
store:
  raft:
    last_log_term: 3439
    last_snapshot_index: 99438
    last_snapshot_term: 3438
    protocol_version_min: 0
    state: Leader
    applied_index: 99460
    fsm_pending: 0
    last_log_index: 99460
    voter: true
    protocol_version: 3
    bolt:
      FreePageN: 4359
      PendingPageN: 10
      FreeAlloc: 17895424
      FreelistInuse: 34968
      TxN: 2798
      OpenTxN: 0
      TxStats:
        CursorCount: 5717
        NodeCount: 511
        Rebalance: 770
        Split: 11
        Write: 199
        PageAlloc: 1982464
        NodeDeref: 0
        RebalanceTime: 1219664
        Spill: 119
        SpillTime: 710407
        WriteTime: 66289962
        PageCount: 484
    latest_configuration: [{Suffrage:Voter ID:4 Address:10.0.4.241:4002} {Suffrage:Voter ID:6 Address:10.0.2.204:4002} {Suffrage:Voter ID:5 Address:10.0.6.13:4002}]
    latest_configuration_index: 0
    commit_index: 99460
    num_peers: 2
    term: 3439
    snapshot_version_max: 1
    snapshot_version_min: 0
    last_contact: 0
    log_size: 50339840
    protocol_version_max: 3
  node_id: 5
  reap_timeout: 0s
  db_applied_index: 99460
  leader:
    node_id: 5
    addr: 10.0.6.13:4002
  ready: true
  db_conf:
    fk_constraints: true
  last_applied_index: 99460
  snapshot_interval: 10s
  election_timeout: 1s
  apply_timeout: 10s
  dir_size: 620940538
  dir_size_friendly: 621 MB
  fsm_index: 99460
  no_freelist_sync: false
  open: true
  snapshot_store:
    dir: /home/ec2-user/rqlite-data/rsnapshots
    snapshots: [3438-99438-1704203680970]
    db_path: /home/ec2-user/rqlite-data/rsnapshots/3438-99438-1704203680970.db
  addr: 10.0.6.13:4002
  nodes: [map[addr:10.0.4.241:4002 id:4 suffrage:Voter] map[addr:10.0.6.13:4002 id:5 suffrage:Voter] map[addr:10.0.2.204:4002 id:6 suffrage:Voter]]
  reap_read_only_timeout: 0s
  trailing_logs: 10240
  dir: /home/ec2-user/rqlite-data
  sqlite3:
    db_size_friendly: 285 MB
    path: /home/ec2-user/rqlite-data/db.sqlite
    size: 285011968
    mem_stats:
      page_size: 4096
      soft_heap_limit: 0
      cache_size: -2000
      freelist_count: 0
      hard_heap_limit: 0
      max_page_count: 1073741823
      page_count: 69586
    pragmas:
      ro:
        foreign_keys: 1
        journal_mode: wal
        synchronous: 1
        wal_autocheckpoint: 1000
      rw:
        foreign_keys: 1
        journal_mode: wal
        synchronous: 0
        wal_autocheckpoint: 0
    ro_dsn: file:/home/ec2-user/rqlite-data/db.sqlite?mode=ro&_fk=true
    rw_dsn: file:/home/ec2-user/rqlite-data/db.sqlite?_fk=true
    version: 3.44.0
    compile_options: [ATOMIC_INTRINSICS=1 COMPILER=gcc-9.4.0 DEFAULT_AUTOVACUUM DEFAULT_CACHE_SIZE=-2000 DEFAULT_FILE_FORMAT=4 DEFAULT_JOURNAL_SIZE_LIMIT=-1 DEFAULT_MMAP_SIZE=0 DEFAULT_PAGE_SIZE=4096 DEFAULT_PCACHE_INITSZ=20 DEFAULT_RECURSIVE_TRIGGERS DEFAULT_SECTOR_SIZE=4096 DEFAULT_SYNCHRONOUS=2 DEFAULT_WAL_AUTOCHECKPOINT=1000 DEFAULT_WAL_SYNCHRONOUS=1 DEFAULT_WORKER_THREADS=0 ENABLE_DBSTAT_VTAB ENABLE_FTS3 ENABLE_FTS3_PARENTHESIS ENABLE_FTS5 ENABLE_RTREE ENABLE_UPDATE_DELETE_LIMIT MALLOC_SOFT_LIMIT=1024 MAX_ATTACHED=10 MAX_COLUMN=2000 MAX_COMPOUND_SELECT=500 MAX_DEFAULT_PAGE_SIZE=8192 MAX_EXPR_DEPTH=1000 MAX_FUNCTION_ARG=127 MAX_LENGTH=1000000000 MAX_LIKE_PATTERN_LENGTH=50000 MAX_MMAP_SIZE=0x7fff0000 MAX_PAGE_COUNT=1073741823 MAX_PAGE_SIZE=65536 MAX_SQL_LENGTH=1000000000 MAX_TRIGGER_DEPTH=1000 MAX_VARIABLE_NUMBER=32766 MAX_VDBE_OP=250000000 MAX_WORKER_THREADS=8 MUTEX_PTHREADS OMIT_DEPRECATED OMIT_LOAD_EXTENSION OMIT_SHARED_CACHE SYSTEM_MALLOC TEMP_STORE=1 THREADSAFE=1]
    conn_pool_stats:
      ro:
        open_connections: 1
        in_use: 0
        wait_count: 0
        wait_duration: 0
        max_idle_closed: 0
        max_idle_time_closed: 2
        max_lifetime_closed: 0
        max_open_connections: 0
        idle: 1
      rw:
        max_open_connections: 1
        open_connections: 1
        in_use: 0
        wait_count: 0
        max_idle_closed: 0
        idle: 1
        wait_duration: 0
        max_idle_time_closed: 0
        max_lifetime_closed: 0
    db_size: 285024256
    wal_size: 510912
  observer:
    dropped: 0
    observed: 227
  request_marshaler:
    compression_batch: 50
    compression_size: 1024
    force_compression: false
  snapshot_threshold: 8192
  heartbeat_timeout: 1s
build:
  compiler: gc
  version: v8.14.1
  branch: master
  build_time: 2023-12-31T15:32:09-0500
  commit: 4b27607127c6e799fb14a1cc71c81116239595d6
cluster:
  addr: 10.0.6.13:4002
  api_addr: 10.0.6.13:4001
  https: false
http:
  queue:
    _default:
      timeout: 50ms
      batch_size: 128
      max_size: 1024
      sequence_number: 0
  tls:
    enabled: false
  auth: enabled
  bind_addr: 10.0.6.13:4001
  cluster:
    timeout: 30s
    conn_pool_stats:
      10.0.2.204:4002:
        idle: 4
        max_open_connections: 64
        open_connections: 4
      10.0.4.241:4002:
        idle: 1
        max_open_connections: 64
        open_connections: 5
      10.0.6.13:4002:
        idle: 4
        max_open_connections: 64
        open_connections: 4
    local_node_addr: 10.0.6.13:4002
```
