### ISSUE TITLE
Docker-compose fails opening store

### ISSUE THREAD

**Issue by PedroS11** [rqlite/rqlite#2127]
**What version are you running?**

Latest docker image

**What Operating System are you running?**

MacOS

**Are you using Docker or Kubernetes to run rqlite?**

Using Podman

**Are you running a single node or a cluster?**

Single node

**What did you do?**

I created a single node docker-compose file follwing the steps [here](https://github.com/rqlite/docker-compose/tree/master/rqliteSingleNode) and the container throws while initialization.

Here's my docker-compose

```
services:
  rqlite:
      ports:
        - 4001:4001
        - 4002:4002
      image: rqlite/rqlite:latest
      container_name: myrqlite-container-1
      hostname: myrqlite-host-1
      volumes:
        - ./data:/rqlite/file/data
      environment:
        NODE_ID: myrqlite-node-1
        HTTP_ADDR: myrqlite-host-1:4001
        RAFT_ADDR: myrqlite-host-1:4002
        SQLITE_EXTENSIONS: "sqlean,sqlite-vec,misc"
      healthcheck:
        test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://myrqlite-host-1:4001/status"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
```

If i run just `podman run -p 4001:4001 rqlite/rqlite` it works as expected

**What did you expect to happen?**

The container to spin up and create my database

**What happened instead?**

Throws an error opening the store

![Image](https://github.com/user-attachments/assets/e84e34d9-1a46-4a8e-9f7e-f46c5d53928a)
