### ISSUE TITLE
"HttpResponseException: 503 Service Unavailable not leader" in a test of 1000 rows per tx

### ISSUE THREAD

**Issue by little-pan** [rqlite/rqlite#542]
In my test, try to insert 10000000 rows into rqlite cluster of 3 nodes on a centos7 x86_64 local server(IP 192.168.145.101) , the insertion batch size is 1000 rows in a transaction, the client is rqlite-java. 
## The problem description:
```
21:22:21.648 i = 100000
21:22:24.986 i = 200000
21:22:28.787 i = 300000
21:22:32.598 i = 400000
21:22:36.404 i = 500000
21:22:40.204 i = 600000
21:22:44.251 i = 700000
21:22:47.904 i = 800000
21:22:52.303 i = 900000
21:22:56.012 i = 1000000
21:23:01.478 i = 1100000
21:23:06.353 i = 1200000
21:23:11.248 i = 1300000
21:23:15.325 i = 1400000
21:23:20.522 i = 1500000
com.google.api.client.http.HttpResponseException: 503 Service Unavailable
not leader

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1102)
        at com.rqlite.impl.ExecuteRequest.execute(ExecuteRequest.java:19)
        at com.rqlite.impl.RqliteImpl.Execute(RqliteImpl.java:63)
        at Test.main(Test.java:55)
Error: exit, i = 1575000
rows: 1575000, time: 67272ms
```
When inserting 1500000 rows, http 503 error occurs.
The rqlited error logs:
```
# node.2 192.168.145.101:4003
2019/01/10 21:23:24 [WARN] raft: Failed to contact 127.0.0.1:4006 in 557.498279ms
2019/01/10 21:23:24 [WARN] raft: Failed to contact 127.0.0.1:4002 in 586.413732ms
2019/01/10 21:23:24 [WARN] raft: Failed to contact quorum of nodes, stepping down
2019/01/10 21:23:24 [INFO] raft: Node at 127.0.0.1:4004 [Follower] entering Follower state (Leader: "")
2019/01/10 21:23:24 [INFO] raft: aborting pipeline replication to peer 127.0.0.1:4002
2019/01/10 21:23:24 [INFO] raft: aborting pipeline replication to peer 127.0.0.1:4006
2019/01/10 21:23:25 [WARN] raft: Heartbeat timeout from "" reached, starting election
2019/01/10 21:23:25 [INFO] raft: Node at 127.0.0.1:4004 [Candidate] entering Candidate state
2019/01/10 21:23:25 [DEBUG] raft: Votes needed: 2
2019/01/10 21:23:25 [DEBUG] raft: Vote granted from 127.0.0.1:4004. Tally: 1
2019/01/10 21:23:25 [DEBUG] raft: Vote granted from 127.0.0.1:4002. Tally: 2
2019/01/10 21:23:25 [INFO] raft: Election won. Tally: 2
2019/01/10 21:23:25 [INFO] raft: Node at 127.0.0.1:4004 [Leader] entering Leader state
2019/01/10 21:23:25 [INFO] raft: pipelining replication to peer 127.0.0.1:4006
2019/01/10 21:23:25 [INFO] raft: pipelining replication to peer 127.0.0.1:4002
2019/01/10 21:23:25 [DEBUG] raft: Node 127.0.0.1:4004 updated peer set (2): [127.0.0.1:4004 127.0.0.1:4006 127.0.0.1:4002]
# node.1 192.168.145.101:4001
2019/01/10 21:23:25 [DEBUG] raft: Node 127.0.0.1:4002 updated peer set (2): [127.0.0.1:4004 127.0.0.1:4006 127.0.0.1:4002]
2019/01/10 21:23:25 [DEBUG] raft-net: 127.0.0.1:4002 accepted connection from: 127.0.0.1:34498
# node.3 192.168.145.101:4005
2019/01/10 21:23:25 [DEBUG] raft: Node 127.0.0.1:4006 updated peer set (2): [127.0.0.1:4004 127.0.0.1:4006 127.0.0.1:4002]
2019/01/10 21:23:25 [DEBUG] raft-net: 127.0.0.1:4006 accepted connection from: 127.0.0.1:50836
```
## Test case and configuration
rqlite cluster: 
```
./rqlited -http-addr 192.168.145.101:4001 -raft-addr localhost:4002 ./node.1 1>./rq.4001.stdout 2>./rq.4001.stderr &
./rqlited -http-addr 192.168.145.101:4003 -raft-addr localhost:4004 -join 192.168.145.101:4001 ./node.2 1>./rq.4003.stdout 2>./rq.4003.stderr &
./rqlited -http-addr 192.168.145.101:4005 -raft-addr localhost:4006 -join 192.168.145.101:4001 ./node.3 1>./rq.4005.stdout 2>./rq.4005.stderr &
```
test case source:
```java
import com.rqlite.*;
import com.rqlite.dto.*;

import java.util.*;
import java.text.*;

public class Test {

	public static void main(String args[]){
		String sql = null, host = "192.168.145.101";
		int port = 4001;

		if(args.length > 0){
			sql = args[0];
		}
		if(args.length > 1){
			host = args[1];
		}
		if(args.length > 2){
			port = Integer.parseInt(args[2]);
		}

		if(sql == null){
			return;
		}


		final long ts = System.currentTimeMillis();
		// Declare variables.
		ExecuteResults results = null;
		QueryResults rows = null;

		// Get a connection to a rqlite node.
		Rqlite rqlite = RqliteFactory.connect("http", host, port);

		// Insert records
		if(sql.length() == 0){
			int rowNum = 10000000, batch = 1000, start = 0;
			final List<String> sqls = new ArrayList<>(batch);
			final DateFormat df = new SimpleDateFormat("HH:mm:ss.SSS");
			int i = start;
			for(int j = i + rowNum; i < j; ){
				final int n = Math.min(batch, j - start);
				for(int k = 0; k < n; ++k, ++i){
					sql = String.format("delete from accounts where id = %d", i);
					sqls.add(sql);
					sql = String.format("insert into accounts(id, name, balance)values(%d, '%s', %d)", i, "账户-"+i, i%1000000);
					sqls.add(sql);
				}
				results = rqlite.Execute(sqls.toArray(new String[sqls.size()]), true);
				sqls.clear();
				if(results == null){
					System.err.println("Error: exit, i = " + i);
					break;
				}
				if((i%100000) == 0){
					System.out.println(String.format("%s i = %d", df.format(new Date()), i));
				}
			}
			System.out.println(String.format("rows: %d, time: %dms", i - start, (System.currentTimeMillis()-ts)));
		}else{
			// Query some records in the table.
			rows = rqlite.Query(sql, Rqlite.ReadConsistencyLevel.STRONG);
			System.out.println(rows.toString());
		}
	}

}
```

**Comment by otoolep** [comment]
What version are you running? Can you dump the diagnostic output from each node, when you hit this issue:

https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

Also, when you receive the 503, is there any message in the body of the response?

**Comment by little-pan** [comment]
Version info: rqlite -v4.4.0, centos 7 x86_64.

**Comment by little-pan** [comment]
# .status
```
192.168.145.101:4001> .status
build:
  branch: 4.3.0-patch
  build_time: 2019-01-03T19:35:08-0500
  commit: 2e91858e1ee0feee19f4c20c6f56a21261bcd44a
  version: v4.4.0
http:
  redirect: 192.168.145.101:4005
  addr: 192.168.145.101:4001
  auth: disabled
mux:
  addr: 127.0.0.1:4002
  encrypted: false
  timeout: 30s
node:
  start_time: 2019-01-12T10:16:52.640983407+08:00
  uptime: 9m8.9043421s
runtime:
  version: go1.10
  GOARCH: amd64
  GOMAXPROCS: 2
  GOOS: linux
  numCPU: 2
  numGoroutine: 19
store:
  apply_timeout: 10s
  db_conf:
    DSN:
    Memory: true
  dir: /root/rqlite/rqlite-v4.4.0-linux-amd64/node.1
  election_timeout: 1s
  heartbeat_timeout: 1s
  snapshot_threshold: 8192
  addr: 127.0.0.1:4002
  leader: 127.0.0.1:4006
  meta:
    APIPeers:
      127.0.0.1:4002: 192.168.145.101:4001
      127.0.0.1:4004: 192.168.145.101:4003
      127.0.0.1:4006: 192.168.145.101:4005
  open_timeout: 2m0s
  peers: [127.0.0.1:4006 127.0.0.1:4002 127.0.0.1:4004]
  raft:
    term: 266
    commit_index: 5860
    last_log_term: 266
    last_snapshot_term: 0
    num_peers: 2
    last_snapshot_index: 0
    state: Follower
    applied_index: 5860
    fsm_pending: 0
    last_contact: 13.173116ms
    last_log_index: 5860
  sqlite3:
    dns:
    fk_constraints: disabled
    path: :memory:
    version: 3.26.0
```

## .expvar
```
192.168.145.101:4001> .expvar
http:
  executions: 3760
  queries: 3
  backups: 0
memstats:
  Lookups: 2.0854025e+07
  HeapObjects: 36756
  DebugGC: false
  Frees: 1.0984228e+08
  StackSys: 720896
  MSpanSys: 245760
  LastGC: 1.547259952983262e+18
  PauseNs: [41660 72498 127441 124731 53140 56255 58968 117683 67057 975766 85266 28535 57720 67512 68181 64748 109965 158391 76713 103247 34824 658934 51572 70319 69533 75766 27437 2.149375e+06 101534 19214 99298 884615 121696 53226 26475 106516 271391 25840 2.911155e+06 415884 718692 801122 108529 817245 247476 32797 1.0112573e+07 112262 2.794807e+06 28147 45343 49760 25555 46681 23907 187808 74608 60314 86489 254015 84423 60146 57272 160444 32886 55269 96942 920074 53187 30556 53397 65297 33940 519662 1.346879e+06 1.192228e+06 228979 67700 74565 43672 391315 74737 22999 54435 1.0545456e+07 78499 63897 272563 99001 141797 24025 101323 63868 44816 47076 63578 643809 117975 19549 980731 110343 64837 357888 50829 62869 289046 50562 47077 59021 59977 117747 4.286283e+06 1.2274899e+07 61281 80124 325651 67409 2.517296e+06 23003 127996 1.01501e+06 23814 138735 1.2321512e+07 53348 72503 26533 1.014638e+06 27105 226362 70532 33600 94451 32168 54630 58726 168355 99538 1.148131e+06 90242 78465 281042 40869 77031 6768
2 43441 70554 52736 29634 85682 26440 24498 91950 96694 33813 21880 83429 103792 46656 84229 64761 781576 97251 1.205807e+06 26541 44734 135346 61741 98213 1.944609e+06 1.195871e+06 28842 69687 78291 608856 644267 1.033164e+06 100146 57450 1.039334e+06 955447 18722 34045 34543 20135 36569 26065 65193 31679 128061 23262 794986 6.781652e+06 5.333895e+06 20440 31955 31304 40259 80457 73001 90350 163808 71801 2.749198e+06 52871 21562 1.5255561e+07 24409 36375 98898 33438 56952 37992 22269 714130 72235 75304 59973 53723 47006 47309 444090 23747 25835 27056 36670 563392 39134 392152 52074 105846 25235 38007 23197 175736 85724 28547 25461 27147 1.382337e+06 29500 84083 26788 93910 42367 83201 483642 68562 22714 89155 24350 75137 557448 132815 48940 65384]
  TotalAlloc: 9.894772872e+09
  StackInuse: 720896
  BuckHashSys: 1.501302e+06
  NumForcedGC: 0
  GCCPUFraction: 0.006131288665470086
  Mallocs: 1.09879036e+08
  HeapAlloc: 2.10064e+06
  HeapSys: 3.3882112e+07
  MSpanInuse: 46056
  NextGC: 4.194304e+06
  PauseTotalNs: 2.569822775e+09
  HeapIdle: 3.080192e+07
  HeapInuse: 3.080192e+06
  MCacheSys: 16384
  MCacheInuse: 3472
  PauseEnd: [1.5472599450766172e+18 1.5472599451284915e+18 1.547259945181261e+18 1.5472599452359887e+18 1.547259945290525e+18 1.547259945344731e+18 1.547259945395512e+18 1.5472599454503616e+18 1.5472599455023913e+18 1.5472599455780116e+18 1.5472599456307994e+18 1.547259945680291e+18 1.547259945729967e+18 1.5472599457812672e+18 1.5472599458297405e+18 1.5472599458796406e+18 1.5472599459311962e+18 1.547259945982559e+18 1.5472599460262034e+18 1.5472599460792763e+18 1.5472599461558264e+18 1.5472599461898634e+18 1.5472599462435845e+18 1.5472599463210665e+18 1.5472599463580127e+18 1.5472599464192358e+18 1.5472599464811686e+18 1.547259946553707e+18 1.5472599465927962e+18 1.547259946672981e+18 1.547259946744105e+18 1.5472599467878618e+18 1.547259946843475e+18 1.547259946906386e+18 1.5472599469584801e+18 1.5472599470106232e+18 1.5472599470582157e+18 1.5472599471088128e+18 1.5472599471723008e+18 1.547259947232924e+18 1.547259947277852e+18 1.5472599473206113e+18 1.5472599473862697e+18 1.5472599474321597e+18 1.54725994753
14621e+18 1.5472599482363978e+18 1.547259948315888e+18 1.547259948377911e+18 1.5472599484322455e+18 1.5472599484878758e+18 1.5472599485555978e+18 1.5472599490484726e+18 1.5472599491158423e+18 1.5472599491791882e+18 1.5472599492384463e+18 1.547259949312428e+18 1.547259949382846e+18 1.5472599494350674e+18 1.5472599494938028e+18 1.5472599495476662e+18 1.5472599496080786e+18 1.5472599496553748e+18 1.5472599497161167e+18 1.547259949757506e+18 1.5472599498082143e+18 1.547259949854563e+18 1.5472599499135252e+18 1.547259949964365e+18 1.5472599500294838e+18 1.5472599500740093e+18 1.5472599501251607e+18 1.5472599501689897e+18 1.5472599502262536e+18 1.5472599502717028e+18 1.5472599503293942e+18 1.5472599503777743e+18 1.547259950424378e+18 1.547259950476152e+18 1.5472599505538284e+18 1.5472599506103928e+18 1.5472599506747587e+18 1.5472599507187556e+18 1.5472599507943357e+18 1.5472599508610365e+18 1.5472599509258857e+18 1.5472599509693932e+18 1.5472599510219717e+18 1.547259951756686e+18 1.547259952983262e+18 1.54725993324
55483e+18 1.547259933300555e+18 1.5472599333632835e+18 1.5472599334274732e+18 1.5472599334682936e+18 1.5472599335475328e+18 1.5472599335976812e+18 1.5472599336520425e+18 1.547259933703185e+18 1.5472599337608817e+18 1.5472599338174065e+18 1.5472599338988017e+18 1.5472599339590482e+18 1.5472599340487462e+18 1.5472599341181978e+18 1.5472599342157601e+18 1.5472599342795062e+18 1.547259934331929e+18 1.5472599344171034e+18 1.547259934442517e+18 1.5472599344910205e+18 1.5472599345512023e+18 1.5472599346049057e+18 1.5472599347130762e+18 1.5472599347365128e+18 1.5472599347862543e+18 1.5472599348380833e+18 1.5472599348928018e+18 1.5472599349648435e+18 1.5472599349995768e+18 1.5472599350667515e+18 1.54725993513394e+18 1.5472599351968627e+18 1.5472599352472297e+18 1.5472599353144238e+18 1.5472599353820718e+18 1.5472599354509827e+18 1.547259935505876e+18 1.5472599355505792e+18 1.5472599356083364e+18 1.5472599356612024e+18 1.5472599357292823e+18 1.5472599357728543e+18 1.5472599358284956e+18 1.5472599358807557e+18 1.5472599
359433444e+18 1.5472599359930301e+18 1.5472599360426284e+18 1.5472599360920916e+18 1.547259936141537e+18 1.547259936190924e+18 1.547259936785687e+18 1.5472599370696783e+18 1.5472599371487813e+18 1.5472599372317059e+18 1.5472599373209324e+18 1.547259937378882e+18 1.5472599374599862e+18 1.5472599375224264e+18 1.5472599375686354e+18 1.5472599376283249e+18 1.5472599376734558e+18 1.5472599377310305e+18 1.5472599377775409e+18 1.5472599378331244e+18 1.5472599378773235e+18 1.5472599379318262e+18 1.5472599379844032e+18 1.5472599380419226e+18 1.547259938099778e+18 1.5472599381571656e+18 1.5472599382110515e+18 1.5472599382668014e+18 1.5472599383204626e+18 1.5472599383810737e+18 1.5472599384322307e+18 1.5472599384938376e+18 1.547259938543273e+18 1.5472599386030387e+18 1.5472599386503299e+18 1.5472599387149837e+18 1.547259938788597e+18 1.5472599388215508e+18 1.547259938876727e+18 1.5472599389326157e+18 1.5472599389748628e+18 1.5472599390279898e+18 1.5472599390752202e+18 1.5472599391293555e+18 1.5472599392068628e+18 1.5472
599392590723e+18 1.5472599393039887e+18 1.5472599394129275e+18 1.5472599401665418e+18 1.5472599402146808e+18 1.5472599402852495e+18 1.5472599403337306e+18 1.5472599404104412e+18 1.5472599404736102e+18 1.547259940545975e+18 1.5472599406048015e+18 1.5472599407139837e+18 1.5472599408073436e+18 1.5472599408639662e+18 1.54725994090844e+18 1.5472599409531448e+18 1.5472599410037276e+18 1.5472599410806116e+18 1.5472599411495383e+18 1.5472599412112558e+18 1.54725994126711e+18 1.5472599413270449e+18 1.5472599413898831e+18 1.5472599414643812e+18 1.5472599415051177e+18 1.5472599415782295e+18 1.5472599416413304e+18 1.5472599416814856e+18 1.5472599417224637e+18 1.5472599417639222e+18 1.547259941845322e+18 1.547259942503401e+18 1.547259942584249e+18 1.5472599426630807e+18 1.5472599427239818e+18 1.5472599427988664e+18 1.547259942843077e+18 1.5472599429006994e+18 1.5472599429497132e+18 1.5472599430121848e+18 1.547259943060392e+18 1.5472599431178793e+18 1.5472599431701373e+18 1.5472599432244751e+18 1.5472599432815012e+18 1.547
259943333452e+18 1.5472599433838625e+18 1.5472599434389857e+18 1.5472599434853542e+18 1.5472599435450929e+18 1.54725994359656e+18 1.5472599436507302e+18 1.5472599436979395e+18 1.5472599437504394e+18 1.5472599438105009e+18 1.547259943867929e+18 1.5472599439222615e+18 1.5472599439771423e+18 1.547259944019378e+18 1.547259944073834e+18 1.5472599441189786e+18 1.547259944168485e+18 1.5472599442110351e+18 1.5472599442689787e+18 1.5472599443285376e+18 1.5472599443873185e+18 1.5472599444496294e+18 1.5472599445061197e+18 1.547259944551932e+18 1.5472599446098752e+18 1.5472599446540877e+18 1.5472599447143137e+18 1.547259944773091e+18 1.5472599448394499e+18 1.5472599448991572e+18 1.5472599449598712e+18 1.5472599450282383e+18]
  EnableGC: true
  Sys: 3.8471928e+07
  HeapReleased: 2.6427392e+07
  GCSys: 1.57696e+06
  BySize: [map[Size:0 Mallocs:0 Frees:0] map[Size:8 Mallocs:2.0181187e+07 Frees:2.0176961e+07] map[Frees:4.0570499e+07 Size:16 Mallocs:4.0584872e+07] map[Frees:386416 Size:32 Mallocs:393674] map[Size:48 Mallocs:2.8278615e+07 Frees:2.8272353e+07] map[Size:64 Mallocs:212345 Frees:211485] map[Size:80 Mallocs:9.50179e+06 Frees:9.500052e+06] map[Size:96 Mallocs:59257 Frees:57674] map[Size:112 Mallocs:45503 Frees:45474] map[Size:128 Mallocs:24563 Frees:24533] map[Size:144 Mallocs:20909 Frees:20893] map[Size:160 Mallocs:46 Frees:14] map[Size:176 Mallocs:20 Frees:12] map[Size:192 Mallocs:5543 Frees:5540] map[Size:208 Mallocs:13433 Frees:13397] map[Size:224 Mallocs:13410 Frees:13404] map[Mallocs:5 Frees:2 Size:240] map[Size:256 Mallocs:32902 Frees:32868] map[Size:288 Mallocs:19276 Frees:19252] map[Mallocs:9583 Frees:9579 Size:320] map[Size:352 Mallocs:15081 Frees:15069] map[Size:384 Mallocs:1952 Frees:1882] map[Size:416 Mallocs:16 Frees:11] map[Frees:9576 Size:448 Mallocs:9578] map[Size:480 Mallocs:9 Frees:7] map[Size
:512 Mallocs:15231 Frees:15225] map[Size:576 Mallocs:22 Frees:12] map[Size:640 Mallocs:7 Frees:3] map[Size:704 Mallocs:9590 Frees:9586] map[Size:768 Mallocs:3872 Frees:3870] map[Size:896 Mallocs:348 Frees:344] map[Size:1024 Mallocs:23256 Frees:23240] map[Size:1152 Mallocs:345 Frees:341] map[Size:1280 Mallocs:339 Frees:338] map[Size:1408 Mallocs:375 Frees:373] map[Size:1536 Mallocs:13805 Frees:13803] map[Size:1792 Mallocs:1111 Frees:1104] map[Size:2048 Mallocs:10565 Frees:10547] map[Frees:10435 Size:2304 Mallocs:10441] map[Size:2688 Mallocs:732 Frees:730] map[Size:3072 Mallocs:753 Frees:753] map[Size:3200 Mallocs:181 Frees:181] map[Mallocs:9851 Frees:9850 Size:3456] map[Size:4096 Mallocs:27354 Frees:27330] map[Frees:2 Size:4864 Mallocs:2] map[Frees:9575 Size:5376 Mallocs:9578] map[Size:6144 Mallocs:490 Frees:486] map[Frees:264 Size:6528 Mallocs:264] map[Size:6784 Mallocs:178 Frees:178] map[Frees:88 Size:6912 Mallocs:88] map[Size:8192 Mallocs:20072 Frees:20069] map[Size:9472 Mallocs:913 Frees:910] map[Frees:176
 Size:9728 Mallocs:176] map[Mallocs:4594 Frees:4593 Size:10240] map[Size:10880 Mallocs:396 Frees:396] map[Size:12288 Mallocs:9819 Frees:9817] map[Size:13568 Mallocs:4462 Frees:4461] map[Size:14336 Mallocs:136 Frees:136] map[Mallocs:4130 Frees:4128 Size:16384] map[Size:18432 Mallocs:14184 Frees:14182] map[Size:19072 Mallocs:110 Frees:110]]
  Alloc: 2.10064e+06
  OtherSys: 528514
  NumGC: 3673
cmdline: [./rqlited -http-addr 192.168.145.101:4001 -raft-addr localhost:4002 ./node.1]
db:
  execution_errors: 10
  executions: 1.0058018e+07
  queries: 5
  query_transactions: 0
  execute_transactions: 5816
```
