### ISSUE TITLE
connectex: No connection could be made because the target machine actively refused it after http 503

### ISSUE THREAD

**Issue by little-pan** [rqlite/rqlite#544]
## the issue description
Connect to the current leader can execute query, but other node can't do any query after http 503:
```
rqlite --host 192.168.152.100 --port 4003
192.168.152.100:4003> select count(*) from accounts;
+-----------+
| count(*)  |
+-----------+
| 6.836e+06 |
+-----------+
192.168.152.100:4003> select count(*) from accounts;
+-----------+
| count(*)  |
+-----------+
| 6.836e+06 |
+-----------+
192.168.152.100:4003> .status
store:
  heartbeat_timeout: 1s
  meta:
    APIPeers:
      127.0.0.1:4006: :4005
      127.0.0.1:4002: :4001
      127.0.0.1:4004: :4003
  peers: [127.0.0.1:4004 127.0.0.1:4002 127.0.0.1:4006]
  snapshot_threshold: 8192
  sqlite3:
    path: :memory:
    version: 3.26.0
    dns:
    fk_constraints: disabled
  addr: 127.0.0.1:4004
  election_timeout: 1s
  dir: /root/rqlite/rqlite-v4.4.0-linux-amd64/node.2
  leader: 127.0.0.1:4004
  open_timeout: 2m0s
  raft:
    applied_index: 8431
    last_contact: 0
    last_log_index: 8431
    term: 17
    num_peers: 2
    state: Leader
    commit_index: 8431
    fsm_pending: 0
    last_log_term: 17
    last_snapshot_index: 8426
    last_snapshot_term: 7
  apply_timeout: 10s
  db_conf:
    DSN:
    Memory: true
build:
  branch: 4.3.0-patch
  build_time: 2019-01-03T19:35:08-0500
  commit: 2e91858e1ee0feee19f4c20c6f56a21261bcd44a
  version: v4.4.0
http:
  addr: [::]:4003
  auth: disabled
  redirect: :4003
mux:
  addr: 127.0.0.1:4004
  encrypted: false
  timeout: 30s
node:
  start_time: 2019-01-20T21:28:34.992416394+08:00
  uptime: 1h6m16.592921919s
runtime:
  GOMAXPROCS: 2
  GOOS: linux
  numCPU: 2
  numGoroutine: 25
  version: go1.10
  GOARCH: amd64
```
But...
```
rqlite --host 192.168.152.100 --port 4001
192.168.152.100:4001> select count(*) from accounts;
ERR! Post http://:4003/db/query: dial tcp :4003: connectex: No connection could be made because the target machine actively refused it.
192.168.152.100:4001> select count(*) from accounts;
ERR! Post http://:4003/db/query: dial tcp :4003: connectex: No connection could be made because the target machine actively refused it.
192.168.152.100:4001> .status
runtime:
  numGoroutine: 20
  version: go1.10
  GOARCH: amd64
  GOMAXPROCS: 2
  GOOS: linux
  numCPU: 2
store:
  election_timeout: 1s
  heartbeat_timeout: 1s
  leader: 127.0.0.1:4004
  meta:
    APIPeers:
      127.0.0.1:4002: :4001
      127.0.0.1:4004: :4003
      127.0.0.1:4006: :4005
  open_timeout: 2m0s
  peers: [127.0.0.1:4004 127.0.0.1:4002 127.0.0.1:4006]
  apply_timeout: 10s
  db_conf:
    Memory: true
    DSN:
  raft:
    applied_index: 8431
    last_contact: 51.217486ms
    last_log_index: 8431
    num_peers: 2
    term: 17
    commit_index: 8431
    fsm_pending: 0
    last_log_term: 17
    last_snapshot_index: 8425
    last_snapshot_term: 7
    state: Follower
  snapshot_threshold: 8192
  sqlite3:
    path: :memory:
    version: 3.26.0
    dns:
    fk_constraints: disabled
  addr: 127.0.0.1:4002
  dir: /root/rqlite/rqlite-v4.4.0-linux-amd64/node.1
build:
  branch: 4.3.0-patch
  build_time: 2019-01-03T19:35:08-0500
  commit: 2e91858e1ee0feee19f4c20c6f56a21261bcd44a
  version: v4.4.0
http:
  redirect: :4003
  addr: [::]:4001
  auth: disabled
mux:
  addr: 127.0.0.1:4002
  encrypted: false
  timeout: 30s
node:
  start_time: 2019-01-20T21:28:29.150448519+08:00
  uptime: 1h7m43.509918686s
```

## version information
rqlited-v4.4.0, centos 7 x86_64.
