### ISSUE TITLE
rqlite not responsive after several queries with strong level

### ISSUE THREAD

**Issue by EthanSosivio** [rqlite/rqlite#658]
I have 5 rqlite server, each inside a container, that work as one cluster.  
Everything works well but i get inconsistent results from time to time.  
When i try to get them with strong level, after 5000 queries it became unavailable.  
All queries waiting for response and nothing come back.  

this is the command i ran:  
``` bash 
for i in {1..100000}; do curl -G 'rqlite-3.rqlite:4001/db/query?pretty&level=strong' --data-urlencode 'q=SELECT count(*) FROM foo' && echo $1; done
```

This is the status of each node.  
rqlite-0
```
store:
  nodes: [map[addr:10.129.3.192:4002 id:rqlite-0] map[addr:10.130.3.196:4002 id:rqlite-1] map[addr:10.131.3.130:4002 id:rqlite-2] map[addr:10.128.3.177:4002 id:rqlite-3] map[addr:10.129.3.191:4002 id:rqlite-4]]
  raft:
    protocol_version_max: 3
    state: Follower
    applied_index: 2990750
    protocol_version: 3
    protocol_version_min: 0
    snapshot_version_max: 1
    fsm_pending: 0
    latest_configuration: [{Suffrage:Voter ID:rqlite-4 Address:10.129.3.191:4002} {Suffrage:Voter ID:rqlite-3 Address:10.128.3.177:4002} {Suffrage:Voter ID:rqlite-2 Address:10.131.3.130:4002} {Suffrage:Voter ID:rqlite-1 Address:10.130.3.196:4002} {Suffrage:Voter ID:rqlite-0 Address:10.129.3.192:4002}]
    last_log_index: 2990750
    last_log_term: 2457
    commit_index: 2990750
    last_contact: 15.379613ms
    latest_configuration_index: 2941915
    num_peers: 4
    snapshot_version_min: 0
    term: 2457
    last_snapshot_index: 2990747
    last_snapshot_term: 2457
  addr: 10.129.3.192:4002
  apply_timeout: 10s
  node_id: rqlite-0
  sqlite3:
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.30.1
  dir: /node
  leader:
    addr: 10.131.3.130:4002
    node_id: rqlite-2
  snapshot_interval: 3e+10
  db_conf:
    Memory: true
    DSN: 
  election_timeout: 1s
  heartbeat_timeout: 1s
  metadata:
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
    rqlite-1:
      api_addr: rqlite-1.rqlite:4001
    rqlite-2:
      api_addr: rqlite-2.rqlite:4001
    rqlite-3:
      api_addr: rqlite-3.rqlite:4001
    rqlite-4:
      api_addr: rqlite-4.rqlite:4001
  snapshot_threshold: 8192
build:
  branch: master
  build_time: 2020-05-13T13:00:25-0400
  commit: 5f762f01ecf2ad74ea398e20258239fca89777e2
  version: v5.3.0
http:
  addr: 10.129.3.192:4001
  auth: disabled
  redirect: rqlite-2.rqlite:4001
node:
  start_time: 2020-07-22T08:15:43.957164386Z
  uptime: 1h35m0.179950682s
runtime:
  GOARCH: amd64
  GOMAXPROCS: 8
  GOOS: linux
  num_cpu: 8
  num_goroutine: 15
  version: go1.14
```

rqlite-1
```
build:
  branch: master
  build_time: 2020-05-13T13:00:25-0400
  commit: 5f762f01ecf2ad74ea398e20258239fca89777e2
  version: v5.3.0
http:
  addr: 10.130.3.196:4001
  auth: disabled
  redirect: rqlite-2.rqlite:4001
node:
  start_time: 2020-07-22T08:15:34.695951005Z
  uptime: 1h35m54.332090463s
runtime:
  version: go1.14
  GOARCH: amd64
  GOMAXPROCS: 8
  GOOS: linux
  num_cpu: 8
  num_goroutine: 15
store:
  apply_timeout: 10s
  db_conf:
    DSN: 
    Memory: true
  metadata:
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
    rqlite-1:
      api_addr: rqlite-1.rqlite:4001
    rqlite-2:
      api_addr: rqlite-2.rqlite:4001
    rqlite-3:
      api_addr: rqlite-3.rqlite:4001
    rqlite-4:
      api_addr: rqlite-4.rqlite:4001
  heartbeat_timeout: 1s
  raft:
    last_log_term: 2457
    last_snapshot_index: 2990575
    latest_configuration: [{Suffrage:Voter ID:rqlite-4 Address:10.129.3.191:4002} {Suffrage:Voter ID:rqlite-3 Address:10.128.3.177:4002} {Suffrage:Voter ID:rqlite-2 Address:10.131.3.130:4002} {Suffrage:Voter ID:rqlite-1 Address:10.130.3.196:4002} {Suffrage:Voter ID:rqlite-0 Address:10.129.3.192:4002}]
    protocol_version_min: 0
    snapshot_version_max: 1
    snapshot_version_min: 0
    applied_index: 2990750
    commit_index: 2990750
    fsm_pending: 0
    protocol_version_max: 3
    term: 2457
    latest_configuration_index: 2941915
    num_peers: 4
    protocol_version: 3
    state: Follower
    last_contact: 51.36505ms
    last_log_index: 2990750
    last_snapshot_term: 2457
  snapshot_interval: 3e+10
  snapshot_threshold: 8192
  dir: /node
  election_timeout: 1s
  node_id: rqlite-1
  sqlite3:
    fk_constraints: disabled
    path: :memory:
    version: 3.30.1
    dsn: 
  addr: 10.130.3.196:4002
  leader:
    node_id: rqlite-2
    addr: 10.131.3.130:4002
  nodes: [map[addr:10.129.3.192:4002 id:rqlite-0] map[addr:10.130.3.196:4002 id:rqlite-1] map[addr:10.131.3.130:4002 id:rqlite-2] map[addr:10.128.3.177:4002 id:rqlite-3] map[addr:10.129.3.191:4002 id:rqlite-4]]
```

rqlite-2
```
http:
  redirect: rqlite-2.rqlite:4001
  addr: 10.131.3.130:4001
  auth: disabled
node:
  start_time: 2020-07-22T08:14:38.001204811Z
  uptime: 1h37m36.043298008s
runtime:
  GOOS: linux
  num_cpu: 8
  num_goroutine: 859
  version: go1.14
  GOARCH: amd64
  GOMAXPROCS: 8
store:
  node_id: rqlite-2
  snapshot_interval: 3e+10
  snapshot_threshold: 8192
  nodes: [map[addr:10.129.3.192:4002 id:rqlite-0] map[addr:10.130.3.196:4002 id:rqlite-1] map[addr:10.131.3.130:4002 id:rqlite-2] map[addr:10.128.3.177:4002 id:rqlite-3] map[addr:10.129.3.191:4002 id:rqlite-4]]
  raft:
    last_contact: 0
    last_log_index: 2990750
    last_log_term: 2457
    latest_configuration: [{Suffrage:Voter ID:rqlite-4 Address:10.129.3.191:4002} {Suffrage:Voter ID:rqlite-3 Address:10.128.3.177:4002} {Suffrage:Voter ID:rqlite-2 Address:10.131.3.130:4002} {Suffrage:Voter ID:rqlite-1 Address:10.130.3.196:4002} {Suffrage:Voter ID:rqlite-0 Address:10.129.3.192:4002}]
    latest_configuration_index: 2941915
    state: Leader
    commit_index: 2990750
    fsm_pending: 10
    term: 2457
    protocol_version: 3
    snapshot_version_max: 1
    snapshot_version_min: 0
    last_snapshot_index: 2982244
    num_peers: 4
    last_snapshot_term: 2457
    protocol_version_min: 0
    applied_index: 2990750
    protocol_version_max: 3
  addr: 10.131.3.130:4002
  apply_timeout: 10s
  election_timeout: 1s
  sqlite3:
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.30.1
  db_conf:
    DSN: 
    Memory: true
  dir: /node
  heartbeat_timeout: 1s
  leader:
    node_id: rqlite-2
    addr: 10.131.3.130:4002
  metadata:
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
    rqlite-1:
      api_addr: rqlite-1.rqlite:4001
    rqlite-2:
      api_addr: rqlite-2.rqlite:4001
    rqlite-3:
      api_addr: rqlite-3.rqlite:4001
    rqlite-4:
      api_addr: rqlite-4.rqlite:4001
build:
  build_time: 2020-05-13T13:00:25-0400
  commit: 5f762f01ecf2ad74ea398e20258239fca89777e2
  version: v5.3.0
  branch: master
```

rqlite-3
```
build:
  branch: master
  build_time: 2020-05-13T13:00:25-0400
  commit: 5f762f01ecf2ad74ea398e20258239fca89777e2
  version: v5.3.0
http:
  addr: 10.128.3.177:4001
  auth: disabled
  redirect: rqlite-2.rqlite:4001
node:
  start_time: 2020-07-22T08:13:49.117951613Z
  uptime: 1h39m8.929730776s
runtime:
  GOARCH: amd64
  GOMAXPROCS: 8
  GOOS: linux
  num_cpu: 8
  num_goroutine: 12
  version: go1.14
store:
  heartbeat_timeout: 1s
  addr: 10.128.3.177:4002
  node_id: rqlite-3
  snapshot_interval: 3e+10
  snapshot_threshold: 8192
  election_timeout: 1s
  nodes: [map[addr:10.129.3.192:4002 id:rqlite-0] map[addr:10.130.3.196:4002 id:rqlite-1] map[addr:10.131.3.130:4002 id:rqlite-2] map[addr:10.128.3.177:4002 id:rqlite-3] map[addr:10.129.3.191:4002 id:rqlite-4]]
  raft:
    last_log_index: 2990750
    latest_configuration_index: 2941915
    protocol_version_max: 3
    term: 2457
    state: Follower
    applied_index: 2990750
    commit_index: 2990750
    last_contact: 2.351587ms
    last_log_term: 2457
    last_snapshot_term: 2457
    num_peers: 4
    protocol_version_min: 0
    latest_configuration: [{Suffrage:Voter ID:rqlite-4 Address:10.129.3.191:4002} {Suffrage:Voter ID:rqlite-3 Address:10.128.3.177:4002} {Suffrage:Voter ID:rqlite-2 Address:10.131.3.130:4002} {Suffrage:Voter ID:rqlite-1 Address:10.130.3.196:4002} {Suffrage:Voter ID:rqlite-0 Address:10.129.3.192:4002}]
    protocol_version: 3
    fsm_pending: 0
    last_snapshot_index: 2990747
    snapshot_version_max: 1
    snapshot_version_min: 0
  sqlite3:
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.30.1
  apply_timeout: 10s
  db_conf:
    DSN: 
    Memory: true
  dir: /node
  leader:
    addr: 10.131.3.130:4002
    node_id: rqlite-2
  metadata:
    rqlite-3:
      api_addr: rqlite-3.rqlite:4001
    rqlite-4:
      api_addr: rqlite-4.rqlite:4001
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
    rqlite-1:
      api_addr: rqlite-1.rqlite:4001
    rqlite-2:
      api_addr: rqlite-2.rqlite:4001
```

rqlte-4
```
rqlite-4.rqlite:4001> .status
build:
  commit: 5f762f01ecf2ad74ea398e20258239fca89777e2
  version: v5.3.0
  branch: master
  build_time: 2020-05-13T13:00:25-0400
http:
  addr: 10.129.3.191:4001
  auth: disabled
  redirect: rqlite-2.rqlite:4001
node:
  start_time: 2020-07-22T08:13:23.500375143Z
  uptime: 1h40m37.332426074s
runtime:
  version: go1.14
  GOARCH: amd64
  GOMAXPROCS: 8
  GOOS: linux
  num_cpu: 8
  num_goroutine: 12
store:
  snapshot_interval: 3e+10
  db_conf:
    DSN: 
    Memory: true
  leader:
    node_id: rqlite-2
    addr: 10.131.3.130:4002
  nodes: [map[addr:10.129.3.192:4002 id:rqlite-0] map[addr:10.130.3.196:4002 id:rqlite-1] map[addr:10.131.3.130:4002 id:rqlite-2] map[addr:10.128.3.177:4002 id:rqlite-3] map[addr:10.129.3.191:4002 id:rqlite-4]]
  dir: /node
  election_timeout: 1s
  heartbeat_timeout: 1s
  node_id: rqlite-4
  raft:
    fsm_pending: 0
    last_snapshot_index: 2990747
    latest_configuration: [{Suffrage:Voter ID:rqlite-4 Address:10.129.3.191:4002} {Suffrage:Voter ID:rqlite-3 Address:10.128.3.177:4002} {Suffrage:Voter ID:rqlite-2 Address:10.131.3.130:4002} {Suffrage:Voter ID:rqlite-1 Address:10.130.3.196:4002} {Suffrage:Voter ID:rqlite-0 Address:10.129.3.192:4002}]
    num_peers: 4
    protocol_version_min: 0
    state: Follower
    term: 2457
    commit_index: 2990750
    last_log_index: 2990750
    last_snapshot_term: 2457
    latest_configuration_index: 2941915
    protocol_version_max: 3
    snapshot_version_max: 1
    snapshot_version_min: 0
    applied_index: 2990750
    last_contact: 9.376893ms
    last_log_term: 2457
    protocol_version: 3
  snapshot_threshold: 8192
  addr: 10.129.3.191:4002
  apply_timeout: 10s
  metadata:
    rqlite-2:
      api_addr: rqlite-2.rqlite:4001
    rqlite-3:
      api_addr: rqlite-3.rqlite:4001
    rqlite-4:
      api_addr: rqlite-4.rqlite:4001
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
    rqlite-1:
      api_addr: rqlite-1.rqlite:4001
  sqlite3:
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.30.1
```
