### ISSUE TITLE
I deployed rqlite by docker compose but it returned peer error

### ISSUE THREAD

**Issue by iamatsundere** [rqlite/rqlite#771]
Hi, when I deploy rqlite and a service that call rqlite, but I received an error like this

`tried all peers unsuccessfully. here are the results:
   peer #0: http://0.0.0.0:4001/status failed due to Get "http://0.0.0.0:4001/status": dial tcp 0.0.0.0:4001: connect: connection refused`

Here how I write the docker compose file:

```
rqlite:
    image: rqlite/rqlite:5.9.0
    container_name: rqlite
    ports:
      - 4001:4001
      - 4002:4002
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4001/status"]
```

And the connection uri I used is: http://rqlite:4001

Have anyone met that issue and how to fix it?

**Comment by otoolep** [comment]
I don't know what is going on, but `http://0.0.0.0:4001/status` doesn't make sense. `0.0.0.0` is not a routable address, and it makes no sense to perform a HTTP `GET` at the location. 

TBH you haven't given us enough info. Where are you getting that error from?

**Comment by otoolep** [comment]
In otherwords *something* is telling *something* to perform a HTTP GET of an invalid address. I have no idea what *something* is in both cases.

**Comment by techyugadi** [comment]
You may be trying to connect to the docker container running rqlite from outside the docker network. Secondly, the master and slave instances of rqlite should be instantiated in a proper sequence. Kubernetes statefulsets (which can use docker containers underneath) can be one way of creating a cluster in a more reliable way. You could find one such implementation here: [You may be trying to connect to the docker container running rqlite from outside the docker network. Secondly, the master and slave instances of rqlite should be instantiated in a proper sequence. Kubernetes statefulsets (which can use docker containers underneath) can be one way of creating a cluster in a more reliable way. You could find one such implementation here: https://github.com/techyugadi/kubestash/tree/master/stateful/rqlite](https://github.com/techyugadi/kubestash/tree/master/stateful/rqlite)

**Comment by techyugadi** [comment]
You may be trying to connect to the docker container running rqlite from outside the docker network. Secondly, the master and slave instances of rqlite should be instantiated in a proper sequence. Kubernetes statefulsets (which can use docker containers underneath) can be one way of creating a cluster in a more reliable way. You could find one such implementation here: https://github.com/techyugadi/kubestash/tree/master/stateful/rqlite

**Comment by iamatsundere** [comment]
Yeah, sorry for missing information. Here is the code that make the request:

```
func main() {

	route := gin.Default()
	logger := newLogger()

	route.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"POST", "PUT", "GET", "DELETE"},
		AllowHeaders:     []string{"Access-Control-Allow-Headers", "Origin", "Accept", "X-Requested-With", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))

	var conn gorqlite.Connection

	for true {
		conn1, err := gorqlite.Open(viper.GetString("rqlite.uri"))

		_, err1 := conn1.Leader()
		utils.LogInfo("%s\t%s\t%v", "leader", viper.GetString("rqlite.uri"), err1)

		if err != nil {
			utils.LogInfo("RETRY")
			time.Sleep(1 * time.Second)
		} else {
			utils.LogInfo("CONNECTED")
			conn = conn1
			break
		}
	}

	generatorStore := generator.NewGeneratorStore(&conn, logger)
	generatorAPI := generator.NewGeneratorAPI(generatorStore, logger)
	generatorAPI.InitRoute(route, "/id_generator")

	//cleaner := workers.NewCleaner(generatorStore, logger)
	//go cleaner.cleaner()
	route.Run("0.0.0.0:8080")
}
```

I used viper to get configurations, and the value for the rqlite.uri is: http://rqlite:4001. Firstly, I caught the issue when I make a request to rqlite service. Then I traced back and tried to get some information by running: `utils.LogInfo("%s\t%s\t%v", "leader", viper.GetString("rqlite.uri"), err1)` and the result for it is: `leader	http://rqlite:4001	tried all peers unsuccessfully. here are the results:
   peer #0: http://0.0.0.0:4001/status failed due to Get "http://0.0.0.0:4001/status": dial tcp 0.0.0.0:4001: connect: connection refused`

**Comment by iamatsundere** [comment]
> You may be trying to connect to the docker container running rqlite from outside the docker network. Secondly, the master and slave instances of rqlite should be instantiated in a proper sequence. Kubernetes statefulsets (which can use docker containers underneath) can be one way of creating a cluster in a more reliable way. You could find one such implementation here: https://github.com/techyugadi/kubestash/tree/master/stateful/rqlite

About the network issues, I don't think it is the network issue, because when I ran `exec` from the container that use rqlite and tried to run `root@80a2aff7ce8d:/opt/app# curl -i http://rqlite:4001/status`, I've got the return:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Rqlite-Version: v5.10.1
Date: Fri, 19 Feb 2021 02:53:20 GMT
Content-Length: 1512

{"build":{"branch":"master","build_time":"2021-02-08T09:16:43-0500","commit":"918f59f2bb4f7875dbaa14e7c096595026cbc569","version":"v5.10.1"},"http":{"addr":"[::]:4001","auth":"disabled","redirect":"0.0.0.0:4001"},"node":{"start_time":"2021-02-18T12:08:24.074711325Z","uptime":"14h44m55.923164236s"},"runtime":{"GOARCH":"amd64","GOMAXPROCS":8,"GOOS":"linux","num_cpu":8,"num_goroutine":9,"version":"go1.15.7"},"store":{"addr":"[::]:4002","apply_timeout":"10s","db_conf":{"DSN":"","Memory":true},"dir":"/rqlite/file/data","dir_size":32768,"election_timeout":"1s","heartbeat_timeout":"1s","leader":{"addr":"[::]:4002","node_id":"0.0.0.0:4002"},"metadata":{"0.0.0.0:4002":{"api_addr":"0.0.0.0:4001","api_proto":"http"}},"node_id":"0.0.0.0:4002","nodes":[{"id":"0.0.0.0:4002","addr":"[::]:4002"}],"raft":{"applied_index":3,"commit_index":3,"fsm_pending":0,"last_contact":0,"last_log_index":3,"last_log_term":2,"last_snapshot_index":0,"last_snapshot_term":0,"latest_configuration":"[{Suffrage:Voter ID:0.0.0.0:4002 Address:[::]:4002}]","latest_configuration_index":0,"log_size":32768,"num_peers":0,"protocol_version":3,"protocol_version_max":3,"protocol_version_min":0,"snapshot_version_max":1,"snapshot_version_min":0,"state":"Leader","term":2},"request_marshaler":{"compression_batch":5,"compression_size":150,"force_compression":false},"snapshot_interval":30000000000,"snapshot_threshold":8192,"sqlite3":{"db_size":0,"dsn":"","fk_constraints":"disabled","path":":memory:","version":"3.34.0"},"trailing_logs":10240}}
```. 
I think there may be some configuration or environment variables problem.

**Comment by techyugadi** [comment]
Then, could you check the rqlite logs by running 'docker logs' on each rqlite container ? There should be one leader and some followers (i used the term master slave). From the docker compose, it is not clear how many followers are being created, unless we're missing something.

**Comment by iamatsundere** [comment]
Yep, here is the log of rqlite but O think it is fine:

```

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/02/19 03:28:07 rqlited starting, version v5.10.1, commit 918f59f2bb4f7875dbaa14e7c096595026cbc569, branch master
[rqlited] 2021/02/19 03:28:07 go1.15.7, target architecture is amd64, operating system target is linux
[rqlited] 2021/02/19 03:28:07 no preexisting node state detected in /rqlite/file/data, node may be bootstrapping
[rqlited] 2021/02/19 03:28:07 no join addresses set
[store] 2021/02/19 03:28:07 opening store with node ID 0.0.0.0:4002
[store] 2021/02/19 03:28:07 ensuring directory at /rqlite/file/data exists
[store] 2021/02/19 03:28:07 0 preexisting snapshots present
[store] 2021/02/19 03:28:07 first log index: 0, last log index: 0, last command log index: 0:
2021-02-19T03:28:07.619Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/02/19 03:28:07 executing new cluster bootstrap
2021-02-19T03:28:07.619Z [INFO]  raft: entering follower state: follower="Node at [::]:4002 [Follower]" leader=
2021-02-19T03:28:09.451Z [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-02-19T03:28:09.451Z [INFO]  raft: entering candidate state: node="Node at [::]:4002 [Candidate]" term=2
2021-02-19T03:28:09.479Z [INFO]  raft: election won: tally=1
2021-02-19T03:28:09.479Z [INFO]  raft: entering leader state: leader="Node at [::]:4002 [Leader]"
[store] 2021/02/19 03:28:09 waiting for up to 2m0s for application of initial logs
[http] 2021/02/19 03:28:09 service listening on [::]:4001
[rqlited] 2021/02/19 03:28:09 node is ready
```

**Comment by otoolep** [comment]
Something is wrong with the way the node is being started up, probably something simple needs to change. From the status output, for example:
```
"redirect": "0.0.0.0:4001"
```

This doesn't make sense, since redirect is meant to be a routable address. `0.0.0.0` there is wrong.

Can you also show us the output of this?

`curl -i http://rqlite:4001/debug/vars`

**Comment by techyugadi** [comment]
While you debug further, I'm curious why you would need docker compose if you need only 1 node of rqlite (obviously the leader), and not a cluster. Shouldn't a simple docker run be enough ? https://github.com/rqlite/rqlite-docker

**Comment by otoolep** [comment]
Also, pull down the latest Docker tag, 5.10.2. I added some logging to the startup output, to understand this issue better.

**Comment by iamatsundere** [comment]
> Something is wrong with the way the node is being started up, probably something simple needs to change. From the status output, for example:
> 
> ```
> "redirect": "0.0.0.0:4001"
> ```
> 
> This doesn't make sense, since redirect is meant to be a routable address. `0.0.0.0` there is wrong.
> 
> Can you also show us the output of this?
> 
> `curl -i http://rqlite:4001/debug/vars`

I ran as you said and it is the result:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Rqlite-Version: v5.10.2
Date: Sun, 21 Feb 2021 06:40:06 GMT
Transfer-Encoding: chunked

{
"cmdline": ["rqlited","-http-addr","0.0.0.0:4001","-raft-addr","0.0.0.0:4002","/rqlite/file/data"],
"db": {"execute_transactions": 0, "execution_errors": 0, "executions": 0, "queries": 0, "query_transactions": 0},
"http": {"authFail": 0, "authOK": 3, "backups": 0, "executions": 0, "joins": 0, "loads": 0, "queries": 0},
"memstats": {"Alloc":1300776,"TotalAlloc":1300776,"Sys":73614592,"Lookups":0,"Mallocs":11689,"Frees":257,"HeapAlloc":1300776,"HeapSys":66650112,"HeapIdle":64217088,"HeapInuse":2433024,"HeapReleased":64217088,"HeapObjects":11432,"StackInuse":458752,"StackSys":458752,"MSpanInuse":62832,"MSpanSys":65536,"MCacheInuse":13888,"MCacheSys":16384,"BuckHashSys":1445315,"GCSys":4017648,"OtherSys":960845,"NextGC":4473924,"LastGC":0,"PauseTotalNs":0,"PauseNs":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":0,"NumForcedGC":0,"GCCPUFraction":0,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":283,"Frees":0},{"Size":16,"Mallocs":1522,"Frees":0},{"Size":32,"Mallocs":2837,"Frees":0},{"Size":48,"Mallocs":519,"Frees":0},{"Size":64,"Mallocs":403,"Frees":0},{"Size":80,"Mallocs":2307,"Frees":0},{"Size":96,"Mallocs":2433,"Frees":0},{"Size":112,"Mallocs":340,"Frees":0},{"Size":128,"Mallocs":78,"Frees":0},{"Size":144,"Mallocs":62,"Frees":0},{"Size":160,"Mallocs":68,"Frees":0},{"Size":176,"Mallocs":21,"Frees":0},{"Size":192,"Mallocs":25,"Frees":0},{"Size":208,"Mallocs":100,"Frees":0},{"Size":224,"Mallocs":52,"Frees":0},{"Size":240,"Mallocs":2,"Frees":0},{"Size":256,"Mallocs":29,"Frees":0},{"Size":288,"Mallocs":33,"Frees":0},{"Size":320,"Mallocs":21,"Frees":0},{"Size":352,"Mallocs":24,"Frees":0},{"Size":384,"Mallocs":46,"Frees":0},{"Size":416,"Mallocs":19,"Frees":0},{"Size":448,"Mallocs":6,"Frees":0},{"Size":480,"Mallocs":2,"Frees":0},{"Size":512,"Mallocs":4,"Frees":0},{"Size":576,"Mallocs":15,"Frees":0},{"Size":640,"Mallocs":19,"Frees":0},{"Size":704,"Mallocs":6,"Frees":0},{"Size":768,"Mallocs":3,"Frees":0},{"Size":896,"Mallocs":20,"Frees":0},{"Size":1024,"Mallocs":22,"Frees":0},{"Size":1152,"Mallocs":9,"Frees":0},{"Size":1280,"Mallocs":14,"Frees":0},{"Size":1408,"Mallocs":2,"Frees":0},{"Size":1536,"Mallocs":1,"Frees":0},{"Size":1792,"Mallocs":15,"Frees":0},{"Size":2048,"Mallocs":3,"Frees":0},{"Size":2304,"Mallocs":4,"Frees":0},{"Size":2688,"Mallocs":9,"Frees":0},{"Size":3072,"Mallocs":0,"Frees":0},{"Size":3200,"Mallocs":2,"Frees":0},{"Size":3456,"Mallocs":0,"Frees":0},{"Size":4096,"Mallocs":29,"Frees":0},{"Size":4864,"Mallocs":3,"Frees":0},{"Size":5376,"Mallocs":2,"Frees":0},{"Size":6144,"Mallocs":3,"Frees":0},{"Size":6528,"Mallocs":0,"Frees":0},{"Size":6784,"Mallocs":0,"Frees":0},{"Size":6912,"Mallocs":0,"Frees":0},{"Size":8192,"Mallocs":4,"Frees":0},{"Size":9472,"Mallocs":1,"Frees":0},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":8,"Frees":0},{"Size":10880,"Mallocs":0,"Frees":0},{"Size":12288,"Mallocs":0,"Frees":0},{"Size":13568,"Mallocs":0,"Frees":0},{"Size":14336,"Mallocs":0,"Frees":0},{"Size":16384,"Mallocs":1,"Frees":0},{"Size":18432,"Mallocs":0,"Frees":0},{"Size":19072,"Mallocs":0,"Frees":0}]},
"proto": {"num_compressed_bytes": 0, "num_compressed_requests": 0, "num_compression_misses": 0, "num_precompressed_bytes": 0, "num_requests": 0, "num_uncompressed_bytes": 0, "num_uncompressed_requests": 0},
"store": {"num_backups": 0, "num_compressed_commands": 0, "num_legacy_commands": 0, "num_restores": 0, "num_snapshots": 0, "num_uncompressed_commands": 0}
```

I also use image version 5.10.2

**Comment by iamatsundere** [comment]
> While you debug further, I'm curious why you would need docker compose if you need only 1 node of rqlite (obviously the leader), and not a cluster. Shouldn't a simple docker run be enough ? https://github.com/rqlite/rqlite-docker

Yeah, but I want to multiple other services, not only rqlite.

**Comment by otoolep** [comment]
Thanks, looks like you're running the standard Docker config. Let me look into it more.

Your original report states that the system has trouble when something hits the /status endpoint. What is that something? How does is resolve `rqlite`. Because clearly `curl` has no problem resolving `rqlite`. So is there something wrong with the your "service" is resolving `rqlite`?

**Comment by otoolep** [comment]
My unfamiliarity with Docker meant I was mistaken about something. The command-line passed to rqlited works for a single, demonstration node (what's in the rqlite Docker repo), but requires tweaking for your specific setup. You should override the command-line options in this file:

https://github.com/rqlite/rqlite-docker/blob/master/5.10.2/docker-entrypoint.sh

If you are going to tell `rqlited` to listen (for both Raft and HTTP) to 0.0.0.0 (all interfaces), you should also set `-http-adv-addr` and `-raft-adv-addr` so that `rqlited` explicitly broadcasts to other nodes how it can be contacted. What those addresses are dependent on your own setup, I can't tell you what they are.

**Comment by otoolep** [comment]
E.g.

```
rqlited -http-addr 0.0.0.0:4001 -http-adv-addr localhost:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr localhost:4001 data3
```

**Comment by otoolep** [comment]
No more updates, closing.

**Comment by iamatsundere** [comment]
Hi, my apologize for this late reply. I have changed the environment but it does not look like better.

```
  rqlite:
    image: rqlite/rqlite:5.10.2
    container_name: vinlab-rqlite
    ports:
      - 4001:4001
      - 4002:4002
    environment:
      -http-addr: http://vinlab-rqlite:4001
      -http-adv-addr: http://vinlab-rqlite:4001
      -raft-addr: http://vinlab-rqlite:4002
      -raft-adv-addr: http://vinlab-rqlite:4002
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
```

**Comment by iamatsundere** [comment]
To make, maybe my full deployment script can have me to solve the problem

```
version: "3.5"

services:
  idgen:
    image: <my_image>
    container_name: idgen
    environment:
      GORQLITE_TEST_URL: "${RQLITE_URI}"
      GORQLITE_PEER: "${RQLITE_URI}"
      RQLITE__URI: "${RQLITE_URI}"
    ports:
      - 8080
    restart: always
    depends_on:
      - rqlite

  rqlite:
    image: rqlite/rqlite:5.10.2
    container_name: rqlite
    ports:
      - 4001:4001
      - 4002:4002
    environment:
      -http-addr: http://rqlite:4001
      -http-adv-addr: http://rqlite:4001
      -raft-addr: http://rqlite:4002
      -raft-adv-addr: http://rqlite:4002
    volumes:
      - ./data/rqlite:/rqlite/file/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

volumes:
  data01:
    driver: local

```

**Comment by iamatsundere** [comment]
I tried many way, but still get the issue

`tried all peers unsuccessfully. here are the results:\n   peer #0: http://0.0.0.0:4001/db/execute?timings&level=weak&transaction failed due to Post \"http://0.0.0.0:4001/db/execute?timings&level=weak&transaction\": dial tcp 0.0.0.0:4001: connect: connection refused\n`

I have deployed rqlite before using kubernetes, but the rqlite container and the service container are in the same pod. It worked. But when I use docker-compose, some thing is wrong here.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-generator-deployment
spec:
  selector:
    matchLabels:
      app: id-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: id-generator
    spec:
      volumes:
        - name: rqlite-pvc
          persistentVolumeClaim:
            claimName: rqlite-pvc
      containers:
        - name: id-generator
          image: <image>
          ports:
            - containerPort: 8080
              name: id-gen-port
          imagePullPolicy: Always
        - name: rqlite
          image: rqlite/rqlite
          ports:
            - containerPort: 4002
              name: rqlite-raftport
          volumeMounts:
            - name: rqlite-pvc
              mountPath: /rqlite/file/data
```

**Comment by otoolep** [comment]
`-http-adv-addr` and `-http-adv-addr` must be set to the *actual address* you want the nodes to be contacted on.

**Comment by iamatsundere** [comment]
> ```
>       -http-addr: http://rqlite:4001
>       -http-adv-addr: http://rqlite:4001
>       -raft-addr: http://rqlite:4002
>       -raft-adv-addr: http://rqlite:4002
> ```
> 
> What is the value of `rqlite`? Is it 0.0.0.0? Setting, for example, `-http-addr` and `-http-adv-addr` to the same value doesn't make sense, since they default to the same value if you don't set them. Do you understand what does flags are actually doing?

Nope, it just the annotation for the address of a container in Docker, the Docker itself understands this address.

**Comment by otoolep** [comment]
OK, thanks for the update.

I am not a Docker expert, so I can't help you much more I'm afraid. I can tell you exactly what the various command line params do, but you'll need to figure out how to make them work. Plenty of folks have got rqlite working fine in Docker, so it's not something broken with rqlite. You could try the rqlite Google Group for more ideas.

**Comment by iamatsundere** [comment]
Ok thanks, may be I will try the Google Groups.

**Comment by brandonros** [comment]
```yaml
version: "3.3"
services:
  db:
    container_name: db
    image: rqlite/rqlite:7.5.1
    ports:
      - "4001:4001"
      - "4002:4002"
    volumes:
      - ./db/:/rqlite/file/
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4001/status"]
```

running just this in docker-compose, i get 502 leader not found when I try to connect a client to the database server. not sure if i need to pass special `command` to force it into single node mode in Docker?
